[package]
name = "hanabi-client"
version = "0.1.0"
authors = ["Miles Steele <miles@milessteele.com>"]

[dependencies]
hyper = "0.11.2"
futures = "0.1.15"
tokio-core = "0.1.9"
serde = "1.0.14"
serde_json = "1.0.3"
serde_derive = "1.0.14"
error-chain = "0.11.0"
rand = "0.3.16"
